### ISSUE TITLE
Delete Extra Data Folder?

### ISSUE THREAD

**Issue by jh-206** [openwfm/notebooks#3]
The directory https://github.com/openwfm/notebooks/tree/main/data looks redundant. I'll delete it if you aren't using?

PS: If you don't like communicating over github issues let me know...

**Comment by janmandel** [comment]
Looking at the history, I created /data in 8ae82bd467e6e26ff801551dfd5121541dae74c5 to house some data files that were around in the top directory. We now keep such files in /fmda/data and it seems we do not even remember what the files in /data are, so yes they can be deleted.
